In [1]:
import os
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import scanpy as sc

sc.settings.verbosity = 0

In [2]:
import GenKI as gk
from GenKI.preprocesing import build_adata
from GenKI.dataLoader import DataLoader
from GenKI.train import VGAE_trainer
from GenKI import utils

%load_ext autoreload
%autoreload 2

/Users/siam/anaconda3/envs/genki/lib/python3.12/site-packages/anndata/__init__.py:70: FutureWarning: Importing read_csv from `anndata` is deprecated. Import anndata.io.read_csv instead.
  return module_get_attr_redirect(attr_name, deprecated_mapping=_DEPRECATED)
/Users/siam/anaconda3/envs/genki/lib/python3.12/site-packages/anndata/__init__.py:70: FutureWarning: Importing read_excel from `anndata` is deprecated. Import anndata.io.read_excel instead.
  return module_get_attr_redirect(attr_name, deprecated_mapping=_DEPRECATED)
/Users/siam/anaconda3/envs/genki/lib/python3.12/site-packages/anndata/__init__.py:70: FutureWarning: Importing read_hdf from `anndata` is deprecated. Import anndata.io.read_hdf instead.
  return module_get_attr_redirect(attr_name, deprecated_mapping=_DEPRECATED)
/Users/siam/anaconda3/envs/genki/lib/python3.12/site-packages/anndata/__init__.py:70: FutureWarning: Importing read_loom from `anndata` is deprecated. Import anndata.io.read_loom instead.
  return module_get_attr_redirect(attr_name, deprecated_mapping=_DEPRECATED)
/Users/siam/anaconda3/envs/genki/lib/python3.12/site-packages/anndata/__init__.py:70: FutureWarning: Importing read_mtx from `anndata` is deprecated. Import anndata.io.read_mtx instead.
  return module_get_attr_redirect(attr_name, deprecated_mapping=_DEPRECATED)
/Users/siam/anaconda3/envs/genki/lib/python3.12/site-packages/anndata/__init__.py:70: FutureWarning: Importing read_text from `anndata` is deprecated. Import anndata.io.read_text instead.
  return module_get_attr_redirect(attr_name, deprecated_mapping=_DEPRECATED)

In [ ]:
adata = sc.read_h5ad('adata.h5ad')
adata

AnnData object with n_obs × n_vars = 3091 × 5000
    obs: 'Sample', 'Group', 'Batch', 'sample', 'n_genes_by_counts', 'total_counts', 'pct_counts_in_top_50_genes', 'pct_counts_in_top_100_genes', 'pct_counts_in_top_200_genes', 'pct_counts_in_top_500_genes', 'total_counts_mt', 'pct_counts_mt', 'total_counts_ribo', 'pct_counts_ribo', 'total_counts_hb', 'pct_counts_hb', 'n_genes', '_scvi_batch', '_scvi_labels', 'doublet', 'doublet_score', 'singlet_score', 'leiden', 'size_factor', '_indices', '_scvi_sample', 'NTM_DE_eff_size', 'Symptomatic_DA_lfc', 'cell_subtype', 'batch', 'cell_type', 'Age'
    var: 'mt', 'ribo', 'hb', 'n_cells_by_counts', 'mean_counts', 'pct_dropout_by_counts', 'total_counts', 'n_cells', 'highly_variable', 'highly_variable_rank', 'means', 'variances', 'variances_norm'
    uns: 'Group_colors', '_scvi_manager_uuid', '_scvi_uuid', 'cell_type_colors', 'clinical_data', 'leiden', 'leiden_colors', 'neighbors', 'pca', 'rank_genes_groups', 'umap'
    obsm: 'X_mrVI', 'X_pca', 'X_picasso', 'X_scVI', 'X_tsne', 'X_umap'
    varm: 'PCs'
    layers: 'counts', 'scvi_normalized'
    obsp: 'connectivities', 'distances'

In [4]:
# Select top 1000 highly variable genes
sc.pp.highly_variable_genes(adata, n_top_genes=1000, flavor='seurat_v3')
adata = adata[:, adata.var['highly_variable']].copy()

print(f"After HVG selection: {adata.n_obs} cells × {adata.n_vars} genes")
adata

/var/folders/ry/99nx7wld5jjcxhnlkbt0651r0000gn/T/ipykernel_16035/2992170871.py:2: UserWarning: `flavor='seurat_v3'` expects raw count data, but non-integers were found.
  sc.pp.highly_variable_genes(adata, n_top_genes=1000, flavor='seurat_v3')

After HVG selection: 3091 cells × 1000 genes

AnnData object with n_obs × n_vars = 3091 × 1000
    obs: 'Sample', 'Group', 'Batch', 'sample', 'n_genes_by_counts', 'total_counts', 'pct_counts_in_top_50_genes', 'pct_counts_in_top_100_genes', 'pct_counts_in_top_200_genes', 'pct_counts_in_top_500_genes', 'total_counts_mt', 'pct_counts_mt', 'total_counts_ribo', 'pct_counts_ribo', 'total_counts_hb', 'pct_counts_hb', 'n_genes', '_scvi_batch', '_scvi_labels', 'doublet', 'doublet_score', 'singlet_score', 'leiden', 'size_factor', '_indices', '_scvi_sample', 'NTM_DE_eff_size', 'Symptomatic_DA_lfc', 'cell_subtype', 'batch', 'cell_type', 'Age'
    var: 'mt', 'ribo', 'hb', 'n_cells_by_counts', 'mean_counts', 'pct_dropout_by_counts', 'total_counts', 'n_cells', 'highly_variable', 'highly_variable_rank', 'means', 'variances', 'variances_norm'
    uns: 'Group_colors', '_scvi_manager_uuid', '_scvi_uuid', 'cell_type_colors', 'clinical_data', 'leiden', 'leiden_colors', 'neighbors', 'pca', 'rank_genes_groups', 'umap', 'hvg'
    obsm: 'X_mrVI', 'X_pca', 'X_picasso', 'X_scVI', 'X_tsne', 'X_umap'
    varm: 'PCs'
    layers: 'counts', 'scvi_normalized'
    obsp: 'connectivities', 'distances'

In [5]:
from GenKI.preprocesing import build_adata

# Preprocess your raw adata
adata = build_adata(
    adata,                    # Your raw AnnData object
    log_normalize=True,       # Optional: log-normalize counts
    scale_data=True,          # Required: creates adata.layers["norm"] and standardizes adata.X
    as_sparse=True,           # Optional: store as sparse matrix
    uppercase=True,           # Optional: convert gene names to uppercase
)

In [19]:
# Search for FOS in var names
ko = 'FOS'

gene_indices = np.where(adata.var_names.str.contains(ko))[0]
print(f"{ko} found at indices: {gene_indices}")

# If found, display the gene names
if len(gene_indices) > 0:
    print(f"{ko} gene names:")
    for idx in gene_indices:
        print(f"Index {idx}: {adata.var_names[idx]}")
else:
    print(f"{ko} not found in var names")

FOS found at indices: [295 296 297]
FOS gene names:
Index 295: FOS
Index 296: FOSB
Index 297: FOSL1

In [8]:
# gene to ko
adata.var_names[295]

'FOS'

In [9]:
# load data

data_wrapper =  DataLoader(
                adata, # adata object
                target_gene = [295], # KO gene name/index
                target_cell = None, # obsname for cell type, if none use all
                obs_label = "cell_type", # colname for genes
                GRN_file_dir = "GRNs", # folder name for GRNs
                rebuild_GRN = True, # whether build GRN by pcNet
                pcNet_name = "pcNet_example", # GRN file name
                verbose = True, # whether verbose
                n_cpus = 12, # multiprocessing
                )

data_wt = data_wrapper.load_data()
data_ko = data_wrapper.load_kodata()

use all the cells (3091) in adata
build GRN

2026-03-13 09:18:14,409	INFO worker.py:2013 -- Started a local Ray instance.
/Users/siam/anaconda3/envs/genki/lib/python3.12/site-packages/ray/_private/worker.py:2052: FutureWarning: Tip: In future versions of Ray, Ray will no longer override accelerator visible devices env var if num_gpus=0 or num_gpus=None (default). To enable this behavior and turn off this error message, set RAY_ACCEL_ENV_VAR_OVERRIDE_ON_ZERO=0
  warnings.warn(

ray init, using 12 CPUs
execution time of making pcNet: 767.66 s
GRN has been built and saved in "GRNs/pcNet_example.npz"
init completed

In [10]:
# init trainer

hyperparams = {"epochs": 100, 
               "lr": 7e-4, 
               "beta": 1e-4, 
               "seed": 8096}
log_dir=None 

sensei = VGAE_trainer(data_wt, 
                     epochs=hyperparams["epochs"], 
                     lr=hyperparams["lr"], 
                     log_dir=log_dir, 
                     beta=hyperparams["beta"],
                     seed=hyperparams["seed"],
                     verbose=True,
                     )

In [11]:
# %%timeit
sensei.train()

Epoch: 000, Loss: 1.8038, AUROC: 0.9297, AP: 0.9365
Epoch: 001, Loss: 1.7513, AUROC: 0.9558, AP: 0.9527
Epoch: 002, Loss: 1.6875, AUROC: 0.9546, AP: 0.9511
Epoch: 003, Loss: 1.7128, AUROC: 0.9522, AP: 0.9488
Epoch: 004, Loss: 1.6913, AUROC: 0.9511, AP: 0.9477
Epoch: 005, Loss: 1.7003, AUROC: 0.9507, AP: 0.9473
Epoch: 006, Loss: 1.6549, AUROC: 0.9505, AP: 0.9472
Epoch: 007, Loss: 1.6403, AUROC: 0.9506, AP: 0.9473
Epoch: 008, Loss: 1.6228, AUROC: 0.9510, AP: 0.9476
Epoch: 009, Loss: 1.5738, AUROC: 0.9515, AP: 0.9481
Epoch: 010, Loss: 1.5951, AUROC: 0.9523, AP: 0.9488
Epoch: 011, Loss: 1.5531, AUROC: 0.9531, AP: 0.9495
Epoch: 012, Loss: 1.5376, AUROC: 0.9540, AP: 0.9503
Epoch: 013, Loss: 1.5835, AUROC: 0.9549, AP: 0.9511
Epoch: 014, Loss: 1.5754, AUROC: 0.9559, AP: 0.9521
Epoch: 015, Loss: 1.5319, AUROC: 0.9571, AP: 0.9530
Epoch: 016, Loss: 1.5204, AUROC: 0.9582, AP: 0.9540
Epoch: 017, Loss: 1.5157, AUROC: 0.9592, AP: 0.9549
Epoch: 018, Loss: 1.5359, AUROC: 0.9602, AP: 0.9558
Epoch: 019, Loss: 1.5495, AUROC: 0.9612, AP: 0.9566
Epoch: 020, Loss: 1.5275, AUROC: 0.9620, AP: 0.9573
Epoch: 021, Loss: 1.5313, AUROC: 0.9627, AP: 0.9579
Epoch: 022, Loss: 1.4918, AUROC: 0.9632, AP: 0.9583
Epoch: 023, Loss: 1.4878, AUROC: 0.9636, AP: 0.9586
Epoch: 024, Loss: 1.4339, AUROC: 0.9639, AP: 0.9588
Epoch: 025, Loss: 1.4754, AUROC: 0.9640, AP: 0.9588
Epoch: 026, Loss: 1.4785, AUROC: 0.9640, AP: 0.9588
Epoch: 027, Loss: 1.4681, AUROC: 0.9638, AP: 0.9586
Epoch: 028, Loss: 1.5475, AUROC: 0.9636, AP: 0.9584
Epoch: 029, Loss: 1.4996, AUROC: 0.9633, AP: 0.9581
Epoch: 030, Loss: 1.4888, AUROC: 0.9630, AP: 0.9577
Epoch: 031, Loss: 1.5040, AUROC: 0.9626, AP: 0.9574
Epoch: 032, Loss: 1.4640, AUROC: 0.9622, AP: 0.9570
Epoch: 033, Loss: 1.4476, AUROC: 0.9618, AP: 0.9567
Epoch: 034, Loss: 1.4588, AUROC: 0.9614, AP: 0.9563
Epoch: 035, Loss: 1.4647, AUROC: 0.9610, AP: 0.9559
Epoch: 036, Loss: 1.4824, AUROC: 0.9606, AP: 0.9556
Epoch: 037, Loss: 1.4222, AUROC: 0.9601, AP: 0.9552
Epoch: 038, Loss: 1.4315, AUROC: 0.9597, AP: 0.9548
Epoch: 039, Loss: 1.4936, AUROC: 0.9592, AP: 0.9544
Epoch: 040, Loss: 1.4856, AUROC: 0.9588, AP: 0.9540
Epoch: 041, Loss: 1.4495, AUROC: 0.9583, AP: 0.9536
Epoch: 042, Loss: 1.4640, AUROC: 0.9578, AP: 0.9531
Epoch: 043, Loss: 1.4528, AUROC: 0.9573, AP: 0.9527
Epoch: 044, Loss: 1.4452, AUROC: 0.9567, AP: 0.9522
Epoch: 045, Loss: 1.4536, AUROC: 0.9562, AP: 0.9518
Epoch: 046, Loss: 1.3918, AUROC: 0.9556, AP: 0.9513
Epoch: 047, Loss: 1.4370, AUROC: 0.9550, AP: 0.9508
Epoch: 048, Loss: 1.4383, AUROC: 0.9544, AP: 0.9503
Epoch: 049, Loss: 1.4099, AUROC: 0.9538, AP: 0.9498
Epoch: 050, Loss: 1.4095, AUROC: 0.9532, AP: 0.9493
Epoch: 051, Loss: 1.4066, AUROC: 0.9526, AP: 0.9487
Epoch: 052, Loss: 1.4312, AUROC: 0.9520, AP: 0.9482
Epoch: 053, Loss: 1.4049, AUROC: 0.9514, AP: 0.9478
Epoch: 054, Loss: 1.4285, AUROC: 0.9509, AP: 0.9473
Epoch: 055, Loss: 1.4450, AUROC: 0.9504, AP: 0.9469
Epoch: 056, Loss: 1.4308, AUROC: 0.9498, AP: 0.9465
Epoch: 057, Loss: 1.4458, AUROC: 0.9493, AP: 0.9461
Epoch: 058, Loss: 1.4464, AUROC: 0.9488, AP: 0.9457
Epoch: 059, Loss: 1.4139, AUROC: 0.9484, AP: 0.9453
Epoch: 060, Loss: 1.3954, AUROC: 0.9479, AP: 0.9449
Epoch: 061, Loss: 1.4137, AUROC: 0.9474, AP: 0.9445
Epoch: 062, Loss: 1.4469, AUROC: 0.9469, AP: 0.9441
Epoch: 063, Loss: 1.3849, AUROC: 0.9464, AP: 0.9437
Epoch: 064, Loss: 1.4247, AUROC: 0.9459, AP: 0.9433
Epoch: 065, Loss: 1.4387, AUROC: 0.9453, AP: 0.9428
Epoch: 066, Loss: 1.3652, AUROC: 0.9448, AP: 0.9424
Epoch: 067, Loss: 1.4076, AUROC: 0.9442, AP: 0.9420
Epoch: 068, Loss: 1.3965, AUROC: 0.9437, AP: 0.9416
Epoch: 069, Loss: 1.3881, AUROC: 0.9432, AP: 0.9412
Epoch: 070, Loss: 1.4054, AUROC: 0.9427, AP: 0.9408
Epoch: 071, Loss: 1.4281, AUROC: 0.9422, AP: 0.9405
Epoch: 072, Loss: 1.3823, AUROC: 0.9417, AP: 0.9401
Epoch: 073, Loss: 1.4114, AUROC: 0.9414, AP: 0.9398
Epoch: 074, Loss: 1.3877, AUROC: 0.9410, AP: 0.9396
Epoch: 075, Loss: 1.4103, AUROC: 0.9407, AP: 0.9394
Epoch: 076, Loss: 1.4158, AUROC: 0.9404, AP: 0.9391
Epoch: 077, Loss: 1.3785, AUROC: 0.9400, AP: 0.9389
Epoch: 078, Loss: 1.4106, AUROC: 0.9397, AP: 0.9386
Epoch: 079, Loss: 1.3634, AUROC: 0.9393, AP: 0.9384
Epoch: 080, Loss: 1.3926, AUROC: 0.9390, AP: 0.9381
Epoch: 081, Loss: 1.3825, AUROC: 0.9387, AP: 0.9379
Epoch: 082, Loss: 1.4051, AUROC: 0.9384, AP: 0.9377
Epoch: 083, Loss: 1.3863, AUROC: 0.9380, AP: 0.9374
Epoch: 084, Loss: 1.3676, AUROC: 0.9376, AP: 0.9371
Epoch: 085, Loss: 1.3775, AUROC: 0.9372, AP: 0.9369
Epoch: 086, Loss: 1.3992, AUROC: 0.9368, AP: 0.9366
Epoch: 087, Loss: 1.3724, AUROC: 0.9364, AP: 0.9363
Epoch: 088, Loss: 1.4103, AUROC: 0.9359, AP: 0.9360
Epoch: 089, Loss: 1.3786, AUROC: 0.9355, AP: 0.9357
Epoch: 090, Loss: 1.3905, AUROC: 0.9351, AP: 0.9355
Epoch: 091, Loss: 1.4048, AUROC: 0.9346, AP: 0.9352
Epoch: 092, Loss: 1.3785, AUROC: 0.9342, AP: 0.9350
Epoch: 093, Loss: 1.3915, AUROC: 0.9340, AP: 0.9348
Epoch: 094, Loss: 1.3548, AUROC: 0.9338, AP: 0.9347
Epoch: 095, Loss: 1.3589, AUROC: 0.9337, AP: 0.9346
Epoch: 096, Loss: 1.3530, AUROC: 0.9336, AP: 0.9345
Epoch: 097, Loss: 1.3512, AUROC: 0.9335, AP: 0.9344
Epoch: 098, Loss: 1.3502, AUROC: 0.9334, AP: 0.9343
Epoch: 099, Loss: 1.3798, AUROC: 0.9333, AP: 0.9342

In [ ]:
sensei.save_model('model')

save model parameters to model/model_ntm_neutrophils.th

In [13]:
# get distance between wt and ko

z_mu_wt, z_std_wt = sensei.get_latent_vars(data_wt)
z_mu_ko, z_std_ko = sensei.get_latent_vars(data_ko)
dis = gk.utils.get_distance(z_mu_ko, z_std_ko, z_mu_wt, z_std_wt, by="KL")

In [14]:
# raw ranked gene list

res_raw = utils.get_generank(data_wt, dis, rank=True)
res_raw.head()

               dis  rank
FOS     222.885655     1
ACAP1     0.008172     2
DIAPH1    0.007997     3
KLF2      0.007582     4
VIM       0.007180     5

In [15]:
# if permutation test

null = sensei.pmt(data_ko, n=100, by="KL")
res = utils.get_generank(data_wt, dis, null,)
#                       save_significant_as = 'gene_list_example')
res

Permutating: 100%|██████████| 100/100 [00:04<00:00, 23.75it/s]

                 dis  index  hit  rank
FOS       222.885655    295  100     1
ACAP1       0.008172      5  100     2
DIAPH1      0.007997    213  100     3
KLF2        0.007582    437  100     4
VIM         0.007180    946  100     5
MYADM       0.007093    541  100     6
MCL1        0.006991    503  100     7
IRF1        0.006958    406  100     8
PRKACA      0.006861    671   99     9
LAPTM5      0.006846    455  100    10
TSC22D3     0.006791    920  100    11
JUND        0.006689    420  100    12
GPSM3       0.006623    335  100    13
LSP1        0.006617    482  100    14
DUSP1       0.006485    227  100    15
PPP1R15A    0.006239    667  100    16
VSIR        0.006103    950   98    17
CRISPLD2    0.006003    184  100    18
STRN4       0.005986    842  100    19
SRGN        0.005872    836   98    20
MYO1F       0.005765    544  100    21
FOSB        0.005675    296   99    22
FTH1        0.005655    301  100    23
S100A8      0.005527    732  100    24
ZFP36       0.005492    970  100    25
S100A9      0.005413    733  100    26
NFKBIA      0.005358    563  100    27
FGR         0.005326    289   99    28
JUNB        0.005177    419  100    29
SPI1        0.005081    828  100    30
MIDN        0.004986    517   99    31
CXCL8       0.004578    197  100    32
KSR1        0.004092    452   96    33
PTGS2       0.004080    685   98    34
C15ORF39    0.003715     93   99    35
PECAM1      0.003221    618   99    36
HCK         0.003132    349   98    37
LTF         0.002989    483   96    38
IL18RAP     0.002955    394   98    39

In [16]:
res = utils.get_generank(data_wt, dis, null, cutoff=0)  # Include all genes with hits

In [17]:
res.to_csv("res.csv", index=True)

In [18]:
res

                dis  index  hit  rank
FOS      222.885655    295  100     1
ACAP1      0.008172      5  100     2
DIAPH1     0.007997    213  100     3
KLF2       0.007582    437  100     4
VIM        0.007180    946  100     5
...             ...    ...  ...   ...
MUC19      0.000032    540    1   112
COPZ2      0.000031    177    1   113
ZNF429     0.000030    982    2   114
EID2B      0.000030    236    1   115
PACSIN1    0.000023    598    3   116

[116 rows x 4 columns]